import JSZip from 'jszip';
import type { GeneratedFile, StyleGuide } from '../types';

export async function exportFilesAsZip(
  files: GeneratedFile[],
  styleGuide: StyleGuide | null,
  projectName: string = 'repo-guardian-export'
): Promise<void> {
  const zip = new JSZip();

  // Add generated files
  files.forEach((file) => {
    zip.file(file.path, file.content);
  });

  // Add README with generation info
  const readme = generateReadme(files, styleGuide, projectName);
  zip.file('README.md', readme);

  // Add style guide if available
  if (styleGuide) {
    const styleGuideContent = generateStyleGuideMarkdown(styleGuide);
    zip.file('STYLE_GUIDE.md', styleGuideContent);
  }

  // Generate and download ZIP
  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${projectName}-${new Date().toISOString().split('T')[0]}.zip`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function generateReadme(files: GeneratedFile[], styleGuide: StyleGuide | null, projectName: string): string {
  return `# ${projectName}

Generated by Repo Guardian on ${new Date().toLocaleString()}

## Generated Files

This package contains ${files.length} generated file${files.length !== 1 ? 's' : ''}:

${files.map((file) => `- \`${file.path}\` - ${file.description}`).join('\n')}

## Repository Patterns

${
  styleGuide
    ? `This code was generated to match the patterns from: ${styleGuide.repository.url}

### Key Patterns Applied
${files[0]?.patterns.map((pattern) => `- ${pattern}`).join('\n') || 'N/A'}
`
    : 'No style guide was used for generation.'
}

## Installation

1. Extract the files to your project directory
2. Install any required dependencies
3. Review and integrate the code into your project

## Notes

- All files follow the detected repository conventions
- Review the STYLE_GUIDE.md for detailed coding standards
- Adjust imports and paths as needed for your project structure

---

Made with ❤️ by Repo Guardian
`;
}

function generateStyleGuideMarkdown(styleGuide: StyleGuide): string {
  return `# Style Guide

Repository: ${styleGuide.repository.url}
Generated: ${new Date(styleGuide.generatedAt).toLocaleString()}

---

${styleGuide.fileOrganization}

---

${styleGuide.namingConventions}

---

${styleGuide.codeStyle}

---

${styleGuide.bestPractices}

---

Made with ❤️ by Repo Guardian
`;
}

export function downloadFile(content: string, filename: string, mimeType: string = 'text/plain'): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

// Made with Bob